### ISSUE TITLE
PNG Import error

### ISSUE THREAD

**Issue by mkny** [expo/expo-github-action#105]
### Description of the bug
When I import a png file, it stops running `expo publish` from github actions. (Local works normally).

### To Reproduce
What steps did you perform which led to this issue?

1. Added simple import to a png file on my project
2. Click manually triggered expo action on my repo
3. It breaks with the following message

Run expo publish

```
[13:46:00] › Expo SDK: 41.0.0
[13:46:00] › Release channel: default
[13:46:00] › Workflow: Managed

[13:46:00] Building optimized bundles and generating sourcemaps...
[13:46:01] Starting Metro Bundler
[13:50:51] assets/icon.png: unsupported file type: undefined (file: /home/runner/work/sysmarketing/sysmarketing/assets/icon.png)
[13:50:51] TypeError: unsupported file type: undefined (file: /home/runner/work/sysmarketing/sysmarketing/assets/icon.png)
    at lookup (/home/runner/work/sysmarketing/sysmarketing/node_modules/image-size/lib/index.js:34:9)
    at module.exports (/home/runner/work/sysmarketing/sysmarketing/node_modules/image-size/lib/index.js:122:12)
    at /home/runner/work/sysmarketing/sysmarketing/node_modules/metro/src/Assets.js:264:34
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/runner/work/sysmarketing/sysmarketing/node_modules/metro/src/Assets.js:52:24)
Error: Process completed with exit code 1.
```

#### Expected behavior
I was expecting to publish normally, as local does.

### Additional context

My yml config file:

```yml
# This is a basic workflow to help you get started with Actions

name: Expo Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN  }}
      - run: yarn install
      - run: expo publish
```

Local versions:
```sh
node -v
v14.0.0

expo --version
4.7.3

yarn -v
1.22.10
```

**Comment by mkny** [comment]
It was a mistake of mine.
Keeping a `.gitattributes` file, that changed my `.png` file as well.
