### ISSUE TITLE
Preview fails with @twilio/conversations

### ISSUE THREAD

**Issue by iM-GeeKy** [expo/expo-github-action#234]
### Description of the bug
@Kudo @byCedric  Using Expo Preview with `@twilio/conversations` causes `Error: Could not create a new EAS Update, reason:
The process '/opt/hostedtoolcache/eas-cli/5.3.0/x64/node_modules/.bin/eas' failed with exit code 1`. This seems to work if `yarn` is used, but fails when `bun` is used. It's possible this is an issue with the Twilio package (I'm not sure where to post this for their visibility) or bun, but someone else might run into this, so I felt it was necessary to post here.

### To Reproduce
What steps did you perform which led to this issue?

1. Go to [example app](https://github.com/iM-GeeKy/bun-expo-app/tree/bun-preview-test).
2. Go to the [preview action](https://github.com/iM-GeeKy/bun-expo-app/actions/runs/6312267921/job/17137968366).
3. Rerun the failed job.
4. See the output.

#### Expected behavior
The job should successfully complete. Without the package, it successfully completes.

#### Actual behavior
```
- Exporting...
  [expo-cli] Starting Metro Bundler
  - Exporting...
  [expo-cli] iOS Bundling failed 11631ms
  - Exporting...
  [expo-cli] 
  - Exporting...
  [expo-cli] Error: Unable to resolve module ./node_modules/tslib/tslib.es6.js from /home/runner/work/bun-expo-app/bun-expo-app/node_modules/@twilio/conversations/dist/client.js: 
  - Exporting...
  [expo-cli] 
  - Exporting...
  [expo-cli] None of these files exist:
  - Exporting...
  [expo-cli]   * node_modules/@twilio/conversations/dist/node_modules/tslib/tslib.es6.js(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs)
  - Exporting...
  [expo-cli]   * node_modules/@twilio/conversations/dist/node_modules/tslib/tslib.es6.js/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs)
  - Exporting...
  [expo-cli]   140 | Object.defineProperty(exports, '__esModule', { value: true });
  - Exporting...
  [expo-cli]   141 |
  - Exporting...
  [expo-cli] > 142 | var tslib_es6 = require('./node_modules/tslib/tslib.es6.js');
  - Exporting...
  [expo-cli]       |                          ^
  - Exporting...
  [expo-cli]   143 | var logger = require('./logger.js');
  - Exporting...
  [expo-cli]   144 | var configuration = require('./configuration.js');
  - Exporting...
  [expo-cli]   145 | var user = require('./user.js');
  - Exporting...
  [expo-cli] Error: Unable to resolve module ./node_modules/tslib/tslib.es6.js from /home/runner/work/bun-expo-app/bun-expo-app/node_modules/@twilio/conversations/dist/client.js: 
  - Exporting...
  [expo-cli] 
  - Exporting...
  [expo-cli] None of these files exist:
  - Exporting...
  [expo-cli]   * node_modules/@twilio/conversations/dist/node_modules/tslib/tslib.es6.js(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs)
  - Exporting...
  [expo-cli]   * node_modules/@twilio/conversations/dist/node_modules/tslib/tslib.es6.js/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs)
  - Exporting...
  [expo-cli]   140 | Object.defineProperty(exports, '__esModule', { value: true });
  - Exporting...
  [expo-cli]   141 |
  - Exporting...
  [expo-cli] > 142 | var tslib_es6 = require('./node_modules/tslib/tslib.es6.js');
  - Exporting...
  [expo-cli]       |                          ^
  - Exporting...
  [expo-cli]   143 | var logger = require('./logger.js');
  - Exporting...
  [expo-cli]   144 | var configuration = require('./configuration.js');
  - Exporting...
  [expo-cli]   145 | var user = require('./user.js');
  - Exporting...
  [expo-cli]     at ModuleResolver.resolveDependency (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:114:15)
  - Exporting...
  [expo-cli]     at DependencyGraph.resolveDependency (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
  - Exporting...
  [expo-cli]     at Object.resolve (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/metro/src/lib/transformHelpers.js:169:21)
  - Exporting...
  [expo-cli]     at Graph._resolveDependencies (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/metro/src/DeltaBundler/Graph.js:473:[35](https://github.com/iM-GeeKy/bun-expo-app/actions/runs/6312267921/job/17137968366#step:7:36))
  - Exporting...
  [expo-cli]     at Graph._processModule (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
  - Exporting...
  [expo-cli]     at async Graph._addDependency (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/metro/src/DeltaBundler/Graph.js:[37](https://github.com/iM-GeeKy/bun-expo-app/actions/runs/6312267921/job/17137968366#step:7:38)2:20)
  - Exporting...
  [expo-cli]     at async Promise.all (index 0)
  - Exporting...
  [expo-cli]     at async Graph._processModule (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
  - Exporting...
  [expo-cli]     at async Graph._addDependency (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
  - Exporting...
  [expo-cli]     at async Promise.all (index 2)
  - Exporting...
  [expo-cli]     at async Graph._processModule (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
  - Exporting...
  [expo-cli]     at async Graph._addDependency (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
  - Exporting...
  [expo-cli]     at async Promise.all (index 2)
  - Exporting...
  [expo-cli]     at async Graph._processModule (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
  - Exporting...
  [expo-cli]     at async Graph._traverseDependenciesForSingleFile (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/metro/src/DeltaBundler/Graph.js:249:5)
  - Exporting...
  [expo-cli]     at async Promise.all (index 0)
  - Exporting...
  [expo-cli]     at async Graph.initialTraverseDependencies (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/metro/src/DeltaBundler/Graph.js:233:5)
  - Exporting...
  [expo-cli]     at async DeltaCalculator._getChangedDependencies (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:229:25)
  - Exporting...
  [expo-cli]     at async DeltaCalculator.getDelta (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:112:16)
  - Exporting...
  [expo-cli]     at async DeltaBundler.buildGraph (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/metro/src/DeltaBundler.js:54:5)
  - Exporting...
  [expo-cli]     at async IncrementalBundler.buildGraphForEntries (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/metro/src/IncrementalBundler.js:66:19)
  - Exporting...
  [expo-cli]     at async IncrementalBundler.buildGraph (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/metro/src/IncrementalBundler.js:146:19)
  - Exporting...
  [expo-cli]     at async Server.build (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/metro/src/Server.js:104:32)
  - Exporting...
  [expo-cli]     at async buildAsync (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/@expo/cli/build/src/export/fork-bundleAsync.js:74:37)
  - Exporting...
  [expo-cli]     at async Promise.all (index 0)
  - Exporting...
  [expo-cli]     at async Object.bundleAsync (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/@expo/cli/build/src/export/fork-bundleAsync.js:115:37)
  - Exporting...
  [expo-cli]     at async Object.createBundlesAsync (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/@expo/cli/build/src/export/createBundles.js:[39](https://github.com/iM-GeeKy/bun-expo-app/actions/runs/6312267921/job/17137968366#step:7:40):21)
  - Exporting...
  [expo-cli]     at async Object.exportAppAsync (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/@expo/cli/build/src/export/exportApp.js:64:21)
  - Exporting...
  [expo-cli]     at async exportAsync (/home/runner/work/bun-expo-app/bun-expo-app/node_modules/@expo/cli/build/src/export/exportAsync.js:45:5)
  - Exporting...
  ✖ Export failed
  /home/runner/work/bun-expo-app/bun-expo-app/node_modules/expo/bin/cli exited with non-zero code: 1
      Error: update command failed.
Error: Could not create a new EAS Update, reason:
The process '/opt/hostedtoolcache/eas-cli/5.3.0/x[64](https://github.com/iM-GeeKy/bun-expo-app/actions/runs/6312267921/job/17137968366#step:7:65)/node_modules/.bin/eas' failed with exit code 1
```

### Additional context
# `npx expo-env-info`
```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
      Watchman: 2023.09.18.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.12 => 49.0.12 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.5 
    npmGlobalPackages:
      eas-cli: 5.2.0
    Expo Workflow: managed
```

# `npx expo-doctor`
```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by iM-GeeKy** [comment]
Is anyone able to look at this? @Kudo

**Comment by Kudo** [comment]
hi there! could you try to run `eas update --auto --json --non-interactive` or `npx expo export` locally to see whether the problem is happened only on preview-action?

**Comment by iM-GeeKy** [comment]
> hi there! could you try to run `eas update --auto --json --non-interactive` or `npx expo export` locally to see whether the problem is happened only on preview-action?

`npx expo export` was successful locally.

**Comment by Kudo** [comment]
@iM-GeeKy [change github action runner](https://github.com/Kudo/bun-expo-app/pull/1/commits/6afb9c74b24c65b1201bed34cc229485b67d7875) did the trick! i think it is more about bun's issue that on ubuntu, the node_modules is not installed correctly.
`Error: Unable to resolve module ./node_modules/tslib/tslib.es6.js from /home/runner/work/bun-expo-app/bun-expo-app/node_modules/@twilio/conversations/dist/client.js`

**Comment by iM-GeeKy** [comment]
> @iM-GeeKy [change github action runner](https://github.com/Kudo/bun-expo-app/pull/1/commits/6afb9c74b24c65b1201bed34cc229485b67d7875) did the trick! i think it is more about bun's issue that on ubuntu, the node_modules is not installed correctly. `Error: Unable to resolve module ./node_modules/tslib/tslib.es6.js from /home/runner/work/bun-expo-app/bun-expo-app/node_modules/@twilio/conversations/dist/client.js`

That worked! Thank you so much, I didn't consider changing what the action runs on, good catch!
