### ISSUE TITLE
Error: Parameter 'commandLine' cannot be null or empty. on self-hosted runners

### ISSUE THREAD

**Issue by fobos531** [expo/expo-github-action#236]
### Description of the bug
I have observed this issue where on the self-hosted runner, my expo action fails even though I have provided the expo token etc.

### To Reproduce
What steps did you perform which led to this issue?

1. Create a self hosted linux runner
2. Point your action to this runner

#### Expected behavior
Expo github action should successfully complete.

#### Actual behavior
```
Installing eas-cli (5.4.0) from cache or with yarn
::group::Validating authenticated account
Validating authenticated account
  ::endgroup::
Error: Parameter 'commandLine' cannot be null or empty.
##[debug]Error: Parameter 'commandLine' cannot be null or empty.
##[debug]    at /home/jakovglavina/actions-runner/_work/_actions/expo/expo-github-action/v8/build/setup/index.js:5805:19
##[debug]    at Generator.next (<anonymous>)
##[debug]    at /home/jakovglavina/actions-runner/_work/_actions/expo/expo-github-action/v8/build/setup/index.js:5784:71
##[debug]    at new Promise (<anonymous>)
##[debug]    at __webpack_modules__.1514.__awaiter (/home/jakovglavina/actions-runner/_work/_actions/expo/expo-github-action/v8/build/setup/index.js:5780:12)
##[debug]    at exec (/home/jakovglavina/actions-runner/_work/_actions/expo/expo-github-action/v8/build/setup/index.js:5802:12)
##[debug]    at authenticate (/home/jakovglavina/actions-runner/_work/_actions/expo/expo-github-action/v8/build/setup/index.js:72452:[28]
##[debug]Node Action run completed with exit code 1
##[debug]MSYS='winsymlinks:nativestrict'
##[debug]Finishing: 🏗 Setup EAS
```
### Additional context

On Github-hosted runners this step passes sucessfully, but again fails on the following step:
![CleanShot 2023-10-11 at 13 37 11@2x](https://github.com/expo/expo-github-action/assets/19533289/a7546b40-6f51-4cdb-867c-44e5ffac18cc)

**Comment by rkcollabro** [comment]
Had the same issue on a Ubuntu 22.04 self-hosted runner. I was able to bypass it via `npm install --global eas-cli` on my self-hosted runner

**Comment by d8vjork** [comment]
same thing here, no idea how to fix, I just swapped to use bun and having this error no matter what

**Comment by knksmith57** [comment]
Has anyone been able to fix this on a project using yarn 4?

This action is broken for me with this same error even after trying:

1. omitting `eas-version` and pre-installing `eas-cli` globally via `npm i -g eas-cli`
2. including `eas-version: latest` and ^ or not installing it globally first
3. quite literally any combination of attempts to preconfigure the runner with `eas-cli` and `@expo/cli`

What package managers + versions are folks running where this is actually working for them?

Very much would appreciate any guidance here; this feels so broken and opaque that I'm out of ideas attempting to debug.

**Comment by vanstinator** [comment]
I'm running on a self hosted runner too, and I'm seeing a similar issue.

I've narrowed this down to the following line (the actual "problem" is a little bit further down the callstack), but the tl;dr is that `which` returns an empty string here. So the command being passed to `exec` is empty, which results in the error string we're seeing. https://github.com/expo/expo-github-action/blob/main/src/expo.ts#L97

I've validated that the `eas-cli` package was installed to the correct `_work/_tool` subdirectory, but for whatever reason the process running the eas setup code isn't looking there. This is only happening on a new runner that I'm setting up with Ansible for the first time. I have another hand-configured runner that works just fine, so I'm working to bisect the difference between the machines. I'll report back if I figure out the specific issue so other folks who run into this can work around the problem.

**Comment by AdamTyler** [comment]
I was facing this issue was well... it seemed to have to do specifically with the machines I had installed yarn v4 onto. The machines with yarn v1 from homebrew seemed to function fine.

The workaround of `npm install --global eas-cli` seemed to fix it for the machines on yarn v4

**Comment by sionnx** [comment]
First, I changed the package manager to pnpm and the workflow ran successfully:  

```YAML
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-cache: false
          expo-cache: false
          eas-version: latest
          packager: pnpm
          token: ${{ secrets.EXPO_TOKEN }}
```

Then I switched the package manager back to yarn, and the problem also disappeared:   

```
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-cache: false
          expo-cache: false
          eas-version: latest
          packager: yarn
          token: ${{ secrets.EXPO_TOKEN }}
```
