### ISSUE TITLE
continuous-deploy-fingerprint error: Could not fetch the project info from "..."

### ISSUE THREAD

**Issue by tristanfrantz** [expo/expo-github-action#299]
### Description of the bug

Running [continuous-deploy-fingerprint action](https://github.com/expo/expo-github-action/tree/main/continuous-deploy-fingerprint) errors with "Could not fetch the project info"

```
Error: Could not fetch the project info from ...
##[debug]Error: Could not fetch the project info from app
##[debug]    at loadProjectConfig (/home/runner/work/_actions/expo/expo-github-action/main/build/continuous-deploy-fingerprint/index.js:42407:15)
##[debug]    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
##[debug]    at async continuousDeployFingerprintAction (/home/runner/work/_actions/expo/expo-github-action/main/build/continuous-deploy-fingerprint/index.js:44539:20)
##[debug]Node Action run completed with exit code 1
##[debug]Finishing:  Continuously Deploy
```

### To Reproduce

workflow:

```
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

env:
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

jobs:
  continuously-deploy:
    runs-on: ubuntu-latest
    concurrency: continuous-deploy-fingerprint-${{ github.event_name != 'pull_request' && 'master' || github.run_id }}
    permissions:
      contents: read # Allow checkout
      pull-requests: write # Allow comments on PRs
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: 18.x

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@main
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Continuously Deploy
        uses: expo/expo-github-action/continuous-deploy-fingerprint@main
        with:
          working-directory: app
          profile: ${{ github.event_name != 'pull_request' && 'production' || 'development' }}
          branch: ${{ github.event_name != 'pull_request' && 'production' || 'development' }}

```

#### Expected behavior
[continuous-deploy-fingerprint action](https://github.com/expo/expo-github-action/tree/main/continuous-deploy-fingerprint) would successfully run

#### Actual behavior
[continuous-deploy-fingerprint action](https://github.com/expo/expo-github-action/tree/main/continuous-deploy-fingerprint) errors with the following output:

```
Error: Could not fetch the project info from ...
##[debug]Error: Could not fetch the project info from app
##[debug]    at loadProjectConfig (/home/runner/work/_actions/expo/expo-github-action/main/build/continuous-deploy-fingerprint/index.js:42407:15)
##[debug]    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
##[debug]    at async continuousDeployFingerprintAction (/home/runner/work/_actions/expo/expo-github-action/main/build/continuous-deploy-fingerprint/index.js:44539:20)
##[debug]Node Action run completed with exit code 1
##[debug]Finishing:  Continuously Deploy
```

### Additional context

using `pnpm@9.0.2` and `node@18.x`

**Comment by wschurman** [comment]
Need repro steps. Mainly what the project looks like that this is being added to. (was it created with `create-expo-app`? what is the app.json? I see it's not in the root directory of the repo).

**Comment by wschurman** [comment]
Closing due to needing repro. Please file a new issue with a repro if this behavior is still happening unexpectedly for you.
