### ISSUE TITLE
`expo publish` command fails with 404 error

### ISSUE THREAD

**Issue by zivl** [expo/expo-github-action#36]
For some reason, my workflow has started to fail over `expo publish` command.
I have not done any change recently in my flow.
here is my `workflow.yml` file:
```yml
name: CI Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_USERNAME }}
          expo-password: ${{ secrets.EXPO_PASSWORD }}
      - run: echo 'Running NPM Install'
      - run: npm ci
      - run: npm run test:ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
      - run: expo publish --non-interactive
        if: github.ref == 'refs/heads/master'
        env:
         EXPO_DEBUG: true
```
In the action log I see `axios` 404 error:
```
Run expo publish --non-interactive
[22:12:04] Unable to find an existing Expo CLI instance for this directory, starting a new one...
[22:12:06] Starting Metro Bundler on port 19001.
[22:12:06] Watch mode is not supported in this environment
[22:12:06] debug Checking for a newer version of React Native
[22:12:06] debug Current version: 0.61.4
[22:12:06] debug No release cache found
[22:12:06] debug No release cache found
[22:12:06] debug Checking for newer releases on GitHub
[22:12:06] debug No release cache found
[22:12:06] debug Saving W/"6d6386b01438c6ef0acd213d304b5839" to cache
[22:12:06] debug No release cache found
[22:12:06] debug No release cache found
[22:12:06] debug Latest release: 0.60.0
[22:12:07] Tunnel ready.
[22:12:07] Publishing to channel 'default'...
[22:12:08] Building iOS bundle
[22:13:46] Building Android bundle
[22:13:46] Finished building JavaScript bundle in 75850ms.
[22:13:46] ::ffff:127.0.0.1 - - [07/Mar/2020:22:13:46 +0000] "GET /node_modules/expo/AppEntry.bundle?dev=false&minify=true&hot=false&platform=ios HTTP/1.1" 200 1557910 "-" "axios/0.19.0"
[22:14:56] Analyzing assets
[22:14:56] Finished building JavaScript bundle in 70400ms.
[22:14:56] ::ffff:127.0.0.1 - - [07/Mar/2020:22:14:56 +0000] "GET /node_modules/expo/AppEntry.bundle?dev=false&minify=true&hot=false&platform=android HTTP/1.1" 200 1567900 "-" "axios/0.19.0"
[22:14:58] Finished building JavaScript bundle in 1635ms.
[22:14:58] ::ffff:127.0.0.1 - - [07/Mar/2020:22:14:58 +0000] "GET /node_modules/expo/AppEntry.assets?dev=false&minify=true&hot=false&platform=ios HTTP/1.1" 200 - "-" "axios/0.19.0"
[22:15:00] Finished building JavaScript bundle in 1532ms.
[22:15:00] ::ffff:127.0.0.1 - - [07/Mar/2020:22:15:00 +0000] "GET /node_modules/expo/AppEntry.assets?dev=false&minify=true&hot=false&platform=android HTTP/1.1" 200 - "-" "axios/0.19.0"
[22:15:00] Uploading assets
[22:15:00] Uploading /assets/locales/messages_en.json
[22:15:01] › Closing Expo server
[22:15:01] › Stopping Metro bundler
[22:15:01] Request failed with status code 404
[22:15:01] Error: Request failed with status code 404
    at createError (/opt/hostedtoolcache/expo-cli/3.13.2/x64/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/hostedtoolcache/expo-cli/3.13.2/x64/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/hostedtoolcache/expo-cli/3.13.2/x64/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
##[error]Process completed with exit code 1.
```
Any ideas?

**Comment by byCedric** [comment]
Thanks for the detailed report! I think this might be related to the open issue [#1674](https://github.com/expo/expo-cli/issues/1647), right? I haven't encountered it myself but the others report that it might be related to specific images. You _can_ try to recreate that image in different formats to see if that's the issue. 

Otherwise pinning the Expo CLI to `3.12.1` [might also fix the issue for now](https://github.com/expo/expo-cli/issues/1647#issuecomment-596203748), at least until it's fully resolved. You can specify the exact version to use by declaring that in your configuration, all you need to do is change `expo-version: 3.x` to `expo-version: 3.12.1`.

Let me know if that worked (temporary) for you, if there are updates on this one I'll let you know and post it here!

<details>
<summary>Your config with the pinned cli version</summary>
<pre>
name: CI Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.12.1
          expo-username: ${{ secrets.EXPO_USERNAME }}
          expo-password: ${{ secrets.EXPO_PASSWORD }}
      - run: echo 'Running NPM Install'
      - run: npm ci
      - run: npm run test:ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
      - run: expo publish --non-interactive
        if: github.ref == 'refs/heads/master'
        env:
         EXPO_DEBUG: true
</pre>
</details>

**Comment by zivl** [comment]
@byCedric  yes it worked!

**Comment by jkhales** [comment]
Thanks for fielding this @byCedric, fix is pushed. Please let us know if there are any more issues!
