### ISSUE TITLE
Input is required, but Expo CLI is in non-interactive mode.

### ISSUE THREAD

**Issue by bitttttten** [expo/expo-github-action#39]
### Description of the bug
Input is required but the GitHub action runs in non-interactive mode.

### Additional context
```sh
 Run yarn publish:ios5s
##[error]Process completed with exit code 1.
Run yarn publish:ios
yarn run v1.22.4
$ expo build:ios
- Making sure project is set up correctly...
[10:17:21] Checking if there is a build in progress...

[10:17:22] Fetching available credentials
[10:17:22] Unable to determine validity of Distribution Certificates.
[10:17:22] CommandError: Input is required, but Expo CLI is in non-interactive mode.
Required input:
> Distribution Certificate (Cert ID: ..., Serial number: ..., Team ID: ...)
>     used by @***/***(com.***.***)
>     ✅ Currently valid on Apple's servers. 
>  Would you like to use this certificate?
    at prompt (/expo-cli@3.16.1/src/prompt.ts:22:11)
    at CreateOrReuseDistributionCert.open (/expo-cli@3.16.1/src/credentials/views/IosDistCert.ts:277:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at CredentialsManager.run (/expo-cli@3.16.1/src/credentials/route.ts:42:12)
    at runCredentialsManager (/expo-cli@3.16.1/src/credentials/route.ts:13:10)
    at IOSBuilder.produceCredentials (/expo-cli@3.16.1/src/commands/build/ios/IOSBuilder.ts:153:7)
    at IOSBuilder.prepareCredentials (/expo-cli@3.16.1/src/commands/build/ios/IOSBuilder.ts:124:7)
    at IOSBuilder.run (/expo-cli@3.16.1/src/commands/build/ios/IOSBuilder.ts:46:7)
    at IOSBuilder.command (/expo-cli@3.16.1/src/commands/build/BaseBuilder.ts:29:7)
    at Command.<anonymous> (/expo-cli@3.16.1/src/exp.ts:85:7) {
  code: 'NON_INTERACTIVE',
  isCommandError: true
}
[10:17:23] Failed to prepare all credentials. 
The next time you build, we will automatically use the following configuration:
[10:17:23]
[10:17:23] Project Credential Configuration:
[10:17:23]   Experience: @***/***, bundle identifier: org.***.***
[10:17:23]     Provisioning profile is missing. It will be generated during the next build
[10:17:23]
[10:17:23] 
[10:17:23] Set EXPO_DEBUG=true in your env to view the stack trace.
```

```sh
name: Publish

on:
  push:
    branches:    
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true
      - run: yarn
      - run: yarn publish:ios
```

```
{
    "scripts": {
        "publish:ios": "expo build:ios"
    }
}
````

How am I able to say "yes" to the prompt here? 🤔

**Comment by bitttttten** [comment]
I ran the publish scripts locally and needed to reconfigure some certificates. After I did this, the builds on CI started working again.

**Comment by byCedric** [comment]
Sorry for my late reply, glad you sorted it out 😄
